# ClaimInsight app with MongoDB
services:
  mongo:
#    Note: use mongo:7 if your linux kernel is between than 6.19 and 7.13
    image: mongo:8.3
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
# Uncomment if you need to connect to MongoDB from your host
#    ports:
#      - "27017:27017"
  app:
    image: myarch/claim-insight:2.15.5
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
      - ./load:/app/load
      - ./etc:/app/etc
    ports:
      - "5080:5080"