# Docker compose file to run ClaimInsight image against local Mongo version
services:
  app:
    image: myarch/claim-insight:2.15.5
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./load:/app/load
      - ./etc:/app/etc
    ports:
      - "5080:5080"
    # if you don't want to use mongo db container, define the host with mongo db here
    extra_hosts:
      - "mongo:host-gateway"