
/****** Object:  Table [dbo].[lz_claim_lines]    Script Date: 6/15/2026 12:51:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
drop table if exists lz_claim_lines;
CREATE TABLE [dbo].[lz_claim_lines](
	[ClaimLineID] [BIGINT] IDENTITY(1,1) NOT NULL,
	[ClaimID] [BIGINT] NULL,
	[Id] [VARCHAR](255) NULL,
	[PatientControlNumber] [VARCHAR](255) NULL,
	[LineControlNumber] [VARCHAR](255) NULL,
	[LineProcedureCode] [VARCHAR](255) NULL,
	[LineProcedureDescFromClaim] [VARCHAR](255) NULL,
	[LineProcedureModifier1Code] [VARCHAR](255) NULL,
	[LineProcedureModifier2Code] [VARCHAR](255) NULL,
	[LineProcedureModifier3Code] [VARCHAR](255) NULL,
	[LineProcedureModifier4Code] [VARCHAR](255) NULL,
	[LineChargeAmount] [VARCHAR](255) NULL,
	[LineUnitType] [VARCHAR](255) NULL,
	[LineUnitCount] [VARCHAR](255) NULL,
	[LinePlaceOfService] [VARCHAR](255) NULL,
	[LinePlaceOfServiceCode] [VARCHAR](255) NULL,
	[LineDiagPointer1] [VARCHAR](255) NULL,
	[LineDiagPointer2] [VARCHAR](255) NULL,
	[LineDiagPointer3] [VARCHAR](255) NULL,
	[LineEmergencyIndicator] [VARCHAR](255) NULL,
	[LineEpsdtIndicator] [VARCHAR](255) NULL,
	[LineFamilyPlanningIndicator] [VARCHAR](255) NULL,
	[LineCopayStatusCode] [VARCHAR](255) NULL,
	[LineServiceDateFrom] [VARCHAR](255) NULL,
	[LineServiceDateTo] [VARCHAR](255) NULL,
	[LinePrescriptionDate] [VARCHAR](255) NULL,
	[LineBeginTherapyDate] [VARCHAR](255) NULL,
	[LineLastSeenDate] [VARCHAR](255) NULL,
	[LineTestPerformedDate] [VARCHAR](255) NULL,
	[LineLastXRayDate] [VARCHAR](255) NULL,
	[LineInitialTreatmentDate] [VARCHAR](255) NULL,
	[LinePriorAuthorization] [VARCHAR](255) NULL,
	[LineReferralNumber] [VARCHAR](255) NULL,
	[LineRepricedReferenceNumber] [VARCHAR](255) NULL,
	[LineAdjustedRepricedReferenceNumber] [VARCHAR](255) NULL,
	[LineNote] [VARCHAR](255) NULL,
	[LineThirdPartyNote] [VARCHAR](255) NULL,
	[LineDrugCode] [VARCHAR](255) NULL,
	[LineDrugQuantity] [VARCHAR](255) NULL,
	[LineDrugUnitType] [VARCHAR](255) NULL,
	[LinePrescriptionNumber] [VARCHAR](255) NULL,
	[LineAttachment1ReportTypeCode] [VARCHAR](255) NULL,
	[LineAttachment1ReportTransmissionCode] [VARCHAR](255) NULL,
	[LineAttachment1ControlNumber] [VARCHAR](255) NULL,
	[LineAttachment2ReportTypeCode] [VARCHAR](255) NULL,
	[LineAttachment2ReportTransmissionCode] [VARCHAR](255) NULL,
	[LineAttachment2ControlNumber] [VARCHAR](255) NULL,
	[LineAttachment3ReportTypeCode] [VARCHAR](255) NULL,
	[LineAttachment3ReportTransmissionCode] [VARCHAR](255) NULL,
	[LineAttachment3ControlNumber] [VARCHAR](255) NULL,
	[LineRenderingProviderIdentifier] [VARCHAR](255) NULL,
	[LineRenderingProviderLastNameOrOrgName] [VARCHAR](255) NULL,
	[LineRenderingProviderFirstName] [VARCHAR](255) NULL,
	[LineRenderingProviderMiddleName] [VARCHAR](255) NULL,
	[LineRenderingProviderProviderTaxonomyCode] [VARCHAR](255) NULL,
	[LineRenderingProviderAdditionalId1Type] [VARCHAR](255) NULL,
	[LineRenderingProviderAdditionalId1Identification] [VARCHAR](255) NULL,
	[LineRenderingProviderAdditionalId2Type] [VARCHAR](255) NULL,
	[LineRenderingProviderAdditionalId2Identification] [VARCHAR](255) NULL,
	[LinePurchasedServiceProviderIdentifier] [VARCHAR](255) NULL,
	[LinePurchasedServiceProviderAdditionalId1Type] [VARCHAR](255) NULL,
	[LinePurchasedServiceProviderAdditionalId1Identification] [VARCHAR](255) NULL,
	[LinePurchasedServiceProviderAdditionalId2Type] [VARCHAR](255) NULL,
	[LinePurchasedServiceProviderAdditionalId2Identification] [VARCHAR](255) NULL,
	[LineServiceFacilityIdentifier] [VARCHAR](255) NULL,
	[LineServiceFacilityName] [VARCHAR](255) NULL,
	[LineServiceFacilityAddressLine] [VARCHAR](255) NULL,
	[LineServiceFacilityAddressLine2] [VARCHAR](255) NULL,
	[LineServiceFacilityAddressCity] [VARCHAR](255) NULL,
	[LineServiceFacilityAddressStateCode] [VARCHAR](255) NULL,
	[LineServiceFacilityAddressZipCode] [VARCHAR](255) NULL,
	[LineServiceFacilityContactName] [VARCHAR](255) NULL,
	[LineServiceFacilityContactContactNumber1Type] [VARCHAR](255) NULL,
	[LineServiceFacilityContactContactNumber1Number] [VARCHAR](255) NULL,
	[LineServiceFacilityContactContactNumber2Type] [VARCHAR](255) NULL,
	[LineServiceFacilityContactContactNumber2Number] [VARCHAR](255) NULL,
	[LineServiceFacilityAdditionalId1Type] [VARCHAR](255) NULL,
	[LineServiceFacilityAdditionalId1Identification] [VARCHAR](255) NULL,
	[LineServiceFacilityAdditionalId2Type] [VARCHAR](255) NULL,
	[LineServiceFacilityAdditionalId2Identification] [VARCHAR](255) NULL,
	[LineSupervisingProviderIdentifier] [VARCHAR](255) NULL,
	[LineSupervisingProviderLastNameOrOrgName] [VARCHAR](255) NULL,
	[LineSupervisingProviderFirstName] [VARCHAR](255) NULL,
	[LineSupervisingProviderMiddleName] [VARCHAR](255) NULL,
	[LineSupervisingProviderAdditionalId1Type] [VARCHAR](255) NULL,
	[LineSupervisingProviderAdditionalId1Identification] [VARCHAR](255) NULL,
	[LineSupervisingProviderAdditionalId2Type] [VARCHAR](255) NULL,
	[LineSupervisingProviderAdditionalId2Identification] [VARCHAR](255) NULL,
	[LineReferringProviderIdentifier] [VARCHAR](255) NULL,
	[LineReferringProviderLastNameOrOrgName] [VARCHAR](255) NULL,
	[LineReferringProviderFirstName] [VARCHAR](255) NULL,
	[LineReferringProviderMiddleName] [VARCHAR](255) NULL,
	[LineReferringProviderAdditionalId1Type] [VARCHAR](255) NULL,
	[LineReferringProviderAdditionalId1Identification] [VARCHAR](255) NULL,
	[LineReferringProviderAdditionalId2Type] [VARCHAR](255) NULL,
	[LineReferringProviderAdditionalId2Identification] [VARCHAR](255) NULL,
	[LineOrderingProviderIdentifier] [VARCHAR](255) NULL,
	[LineOrderingProviderLastNameOrOrgName] [VARCHAR](255) NULL,
	[LineOrderingProviderFirstName] [VARCHAR](255) NULL,
	[LineOrderingProviderMiddleName] [VARCHAR](255) NULL,
	[LineOrderingProviderAddressLine] [VARCHAR](255) NULL,
	[LineOrderingProviderAddressLine2] [VARCHAR](255) NULL,
	[LineOrderingProviderAddressCity] [VARCHAR](255) NULL,
	[LineOrderingProviderAddressStateCode] [VARCHAR](255) NULL,
	[LineOrderingProviderAddressZipCode] [VARCHAR](255) NULL,
	[LineOrderingProviderContactName] [VARCHAR](255) NULL,
	[LineOrderingProviderContactContactNumber1Type] [VARCHAR](255) NULL,
	[LineOrderingProviderContactContactNumber1Number] [VARCHAR](255) NULL,
	[LineOrderingProviderContactContactNumber2Type] [VARCHAR](255) NULL,
	[LineOrderingProviderContactContactNumber2Number] [VARCHAR](255) NULL,
	[LineOrderingProviderAdditionalId1Type] [VARCHAR](255) NULL,
	[LineOrderingProviderAdditionalId1Identification] [VARCHAR](255) NULL,
	[LineOrderingProviderAdditionalId2Type] [VARCHAR](255) NULL,
	[LineOrderingProviderAdditionalId2Identification] [VARCHAR](255) NULL,
	[LineAmbulancePickUpAddressLine] [VARCHAR](255) NULL,
	[LineAmbulancePickUpAddressLine2] [VARCHAR](255) NULL,
	[LineAmbulancePickUpAddressCity] [VARCHAR](255) NULL,
	[LineAmbulancePickUpAddressStateCode] [VARCHAR](255) NULL,
	[LineAmbulancePickUpAddressZipCode] [VARCHAR](255) NULL,
	[LineAmbulanceDropOffLastNameOrOrgName] [VARCHAR](255) NULL,
	[LineAmbulanceDropOffAddressLine] [VARCHAR](255) NULL,
	[LineAmbulanceDropOffAddressLine2] [VARCHAR](255) NULL,
	[LineAmbulanceDropOffAddressCity] [VARCHAR](255) NULL,
	[LineAmbulanceDropOffAddressStateCode] [VARCHAR](255) NULL,
	[LineAmbulanceDropOffAddressZipCode] [VARCHAR](255) NULL,
	[EtlId] [INT] NULL,
	[EtlDate] [DATETIME2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[ClaimLineID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[lz_claim_lines] ADD  CONSTRAINT [df_claim_line_etl_date]  DEFAULT (GETDATE()) FOR [EtlDate]
GO

-- ALTER TABLE [dbo].[lz_claim_lines]  WITH CHECK ADD  CONSTRAINT [FK_lz_claim_lines_claim] FOREIGN KEY([ClaimID])
-- REFERENCES [dbo].[lz_claim] ([ClaimID])
-- GO

-- ALTER TABLE [dbo].[lz_claim_lines] CHECK CONSTRAINT [FK_lz_claim_lines_claim]
-- GO