#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_OUTPUT="$SCRIPT_DIR/../../../content/website/content/docs/ediconvert-api/python-sdk-reference.md"
OUTPUT_FILE="${1:-$DEFAULT_OUTPUT}"
GENERATED_BODY="$(mktemp)"

cleanup() {
    rm -f "$GENERATED_BODY"
}
trap cleanup EXIT

cd "$SCRIPT_DIR"

if ! command -v pydoc-markdown >/dev/null 2>&1; then
    echo "pydoc-markdown is not installed." >&2
    echo "Install it with: python -m pip install '.[docs]'" >&2
    exit 1
fi

pydoc-markdown pydoc-markdown.yml > "$GENERATED_BODY"
mkdir -p "$(dirname "$OUTPUT_FILE")"

{
    cat <<'EOF'
---
---
title: "Python SDK API Reference (2.15)"
description: "Python API reference for version 2.15 of the EDI Converter SDK, including client configuration, conversion, generation, validation, application information, and error handling."
keywords: [edi converter python sdk, python edi api, x12 python sdk, edi conversion python, edi generation python, edi validation python]
slug: python-sdk
aliases:
  - /docs/ediconvert-api/python-sdk-2.15/
menu:
  docs:
    name: Python SDK (2.15)
    parent: edi-converter-doc
    weight: 46
---

<!-- Generated by python/api/generate_python_sdk_reference.sh. Do not edit manually. -->

# Python SDK API Reference (2.15)

Install the SDK from PyPI:

```bash
python -m pip install ediconvert-sdk
```

The `EdiConverterClient` provides grouped clients for EDI conversion, generation, validation, and application information. See the [EDI Converter API reference](/docs/ediconvert-api/reference/) for the underlying HTTP endpoints and schemas.

## Python Object Model

The SDK includes the generated `edi_model` package. Its Pydantic models represent claims, payments, member coverage, validation issues, EDI generation requests, and the supporting objects nested within them. The models are generated from the same OpenAPI schemas used by the API, so this reference does not duplicate every model class and field. See the [JSON schema documentation](/docs/schemas/) for field definitions, descriptions, examples, and mappings to X12 EDI segments and elements.

Model attributes use Python `snake_case` names, while aliases map them to the API's `camelCase` JSON fields. Use Pydantic's `model_validate()` to convert a decoded API object into a typed model. To serialize a model for the API, use `model_dump(by_alias=True, exclude_none=True, mode="json")`.

### General Usage Pattern

Conversion streams can contain different business-object types as well as warnings, errors, and validation issues. Inspect `objectType` before selecting the model class:

```python
import json

from edi_model.all_classes import Payment, ProviderAdjustment
from edi_model.enums import ObjectType
from ediconvert_sdk import EdiConverterClient, handle_warning_error


with EdiConverterClient("http://localhost:5080/api") as client:
    response = client.conversion.to_json_file(
        "835.edi",
        ndjson=True,
        validate=True,
    )

    for line in response.iter_lines():
        data = json.loads(line)

        # Handle ERROR, WARNING, and VALIDATION objects before business objects.
        if handle_warning_error(data):
            continue

        object_type = ObjectType(data["objectType"])
        if object_type is ObjectType.PAYMENT:
            payment = Payment.model_validate(data)
            print(payment.patient_control_number, payment.payment_amount)
        elif object_type is ObjectType.PROVIDER_ADJUSTMENT:
            adjustment = ProviderAdjustment.model_validate(data)
            print(adjustment.fiscal_period_date)
```

EOF
    cat "$GENERATED_BODY"
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"